#!/usr/bin/env python3
"""
DontFeedTheAI — Interactive setup wizard and session launcher.
Everything in one place: setup, deploy, sync, connect, tunnel.

Usage:
    python3 wizard.py              # full interactive setup
    python3 wizard.py deploy       # deploy to VPS
    python3 wizard.py sync         # sync code + rebuild proxy container
    python3 wizard.py connect      # open tunnel + launch Claude
    python3 wizard.py tunnel       # open tunnel only (no Claude)
"""

from __future__ import annotations

import atexit
import getpass
import os
import platform
import re
import secrets
import shlex
import shutil
import signal
import stat
import subprocess
import sys
import tempfile
import time
import urllib.request
from datetime import datetime
from pathlib import Path

# ── Constants ─────────────────────────────────────────────────────────────────

ROOT       = Path(__file__).parent
ENV_FILE   = ROOT / ".env.vps"
REMOTE_DIR   = "/root/DontFeedTheAI"
OLLAMA_PORT  = 11434
INSTALL_CMD  = "dfai"

SYSTEM   = platform.system()
IS_WIN   = SYSTEM == "Windows"
IS_MAC   = SYSTEM == "Darwin"
IS_LINUX = SYSTEM == "Linux"

B  = "\033[1m"
G  = "\033[0;32m"
Y  = "\033[1;33m"
R  = "\033[0;31m"
C  = "\033[0;36m"
N  = "\033[0m"
HR = f"{B}{'─' * 54}{N}"

_RSYNC_EXCLUDE = [
    "--exclude=.env", "--exclude=.env.vps",
    "--exclude=.git", "--exclude=data/",
    "--exclude=__pycache__", "--exclude=*.pyc",
    "--exclude=.venv", "--exclude=*.egg-info",
    "--exclude=.pytest_cache",
]

_SFTP_EXCLUDE = {".git", ".venv", "__pycache__", "data", ".env", ".env.vps", ".pytest_cache"}

_DOCKER_INSTALL = r"""
set -e
if ! command -v docker &>/dev/null; then
    apt-get update -qq && apt-get install -y -qq ca-certificates curl
    curl -fsSL https://get.docker.com | sh
fi
docker --version && docker compose version
"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def ask(prompt: str, default: str = "", secret: bool = False) -> str:
    display = f"  {prompt} [{default}]: " if default else f"  {prompt}: "
    try:
        value = getpass.getpass(display) if secret else input(display).strip()
    except (KeyboardInterrupt, EOFError):
        print()
        sys.exit(0)
    return value or default


def ask_yn(prompt: str, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    raw = ask(f"{prompt} ({hint})", default="y" if default else "n")
    return raw.strip().lower() in ("y", "yes", "")


def header(title: str) -> None:
    print(f"\n{HR}")
    print(f"{B}  {title}{N}")
    print(f"{HR}\n")


def ok(msg: str)   -> None: print(f"  {G}✓{N}  {msg}")
def warn(msg: str) -> None: print(f"  {Y}⚠{N}  {msg}")
def err(msg: str)  -> None: print(f"  {R}✗{N}  {msg}")
def info(msg: str) -> None: print(f"  {C}▸{N}  {msg}")


def detect_ram_gb() -> float | None:
    try:
        import psutil
        return psutil.virtual_memory().total / (1024 ** 3)
    except ImportError:
        pass
    try:
        if IS_MAC:
            out = subprocess.check_output(["sysctl", "-n", "hw.memsize"], text=True)
            return int(out.strip()) / (1024 ** 3)
        if IS_LINUX:
            mem = Path("/proc/meminfo").read_text()
            kb  = int(re.search(r"MemTotal:\s+(\d+)", mem).group(1))
            return kb / (1024 ** 2)
        if IS_WIN:
            out = subprocess.check_output(
                ["wmic", "computersystem", "get", "TotalPhysicalMemory"],
                text=True, shell=True,
            )
            return int(out.strip().split()[-1]) / (1024 ** 3)
    except Exception:
        pass
    return None


def suggest_model(ram_gb: float | None) -> str:
    if ram_gb is None: return "qwen3:1.7b"
    if ram_gb >= 16:   return "qwen3:8b"
    if ram_gb >= 8:    return "qwen3:4b"
    if ram_gb >= 4:    return "qwen3:1.7b"
    return "qwen3:0.6b"


def ssh_available() -> bool:
    return shutil.which("ssh") is not None


def generate_secret() -> str:
    return secrets.token_hex(24)


# ── .env.vps ──────────────────────────────────────────────────────────────────

def write_env(cfg: dict) -> None:
    lines = [
        "# Generated by DontFeedTheAI wizard",
        f"# Platform : {SYSTEM} {platform.machine()}",
        f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "# ── Deployment ───────────────────────────────────────────────",
        f"DEPLOY_MODE={cfg.get('deploy_mode', 'vps')}",
        "",
        "# ── VPS ──────────────────────────────────────────────────────",
        f"VPS_HOST={cfg.get('vps_host', '')}",
        f"PROXY_PORT={cfg.get('proxy_port', '5555')}",
        "",
        "# ── Proxy ────────────────────────────────────────────────────",
        "PORT=8080",
        "HOST=0.0.0.0",
        "",
        "# ── Anthropic ────────────────────────────────────────────────",
        "ANTHROPIC_API_URL=https://api.anthropic.com",
        "",
        "# ── Ollama ───────────────────────────────────────────────────",
        "OLLAMA_HOST=http://localhost:11434",
        f"OLLAMA_MODEL={cfg.get('ollama_model', 'qwen3:1.7b')}",
        "OLLAMA_TIMEOUT=90",
        "LLM_ENABLED=true",
        "",
        "# ── Engagement ───────────────────────────────────────────────",
        f"ENGAGEMENT_ID={cfg.get('engagement_id', 'default')}",
        "",
        "# ── Storage ──────────────────────────────────────────────────",
        "DATA_DIR=./data",
        "DATABASE_PATH=./data/pii_vault.db",
        "",
        "# ── Chunking ─────────────────────────────────────────────────",
        "LLM_CHUNK_SIZE=800",
        "LLM_CHUNK_OVERLAP=150",
        "OLLAMA_NUM_THREADS=6",
    ]
    if cfg.get("pentest_dir"):
        lines += ["", f"PENTEST_DIR={cfg['pentest_dir']}"]
    if cfg.get("ssh_key"):
        lines += ["", f"SSH_KEY={cfg['ssh_key']}"]
    ENV_FILE.write_text("\n".join(lines) + "\n")
    ok(f"Configuration written to {ENV_FILE.name}")


def _load_env() -> dict:
    if not ENV_FILE.exists():
        return {}
    result = {}
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            result[k.strip().lower()] = v.strip()
    return result


def _save_env_key(key: str, value: str) -> None:
    if not ENV_FILE.exists():
        ENV_FILE.write_text(f"{key}={value}\n")
        return
    text = ENV_FILE.read_text()
    lines = []
    found = False
    for line in text.splitlines():
        if line.startswith(f"{key}="):
            lines.append(f"{key}={value}")
            found = True
        else:
            lines.append(line)
    if not found:
        lines.append(f"\n{key}={value}")
    ENV_FILE.write_text("\n".join(lines) + "\n")


# ── SSH helpers (Unix) ────────────────────────────────────────────────────────

_CONTROL_PATH = "/tmp/dfai-ssh-%r@%h:%p"


def _ssh_opts(cfg: dict) -> list[str]:
    key = cfg.get("ssh_key", "")
    opts = [
        "-o", "StrictHostKeyChecking=accept-new",
        "-o", "ConnectTimeout=10",
        "-o", "ControlMaster=auto",
        "-o", f"ControlPath={_CONTROL_PATH}",
        "-o", "ControlPersist=120",
    ]
    if key and Path(key).exists():
        opts += ["-i", key, "-o", "IdentitiesOnly=yes"]
    return opts


def _prime_ssh_agent(cfg: dict) -> None:
    """Ask for SSH passphrase once (hidden) and load the key into the agent.
    After this, all SSH/rsync/scp calls use the agent — no more prompts."""
    if IS_WIN or not shutil.which("ssh-add"):
        return
    key = cfg.get("ssh_key", "")
    # Fall back to common default key paths when none is configured
    if not key or not Path(key).exists():
        for candidate in ("id_ed25519", "id_rsa", "id_ecdsa"):
            p = Path.home() / ".ssh" / candidate
            if p.exists():
                key = str(p)
                break
    if not key or not Path(key).exists():
        return
    key_path = Path(key)

    # Key has no passphrase → add silently and return
    if subprocess.run(
        ["ssh-keygen", "-y", "-P", "", "-f", str(key_path)],
        capture_output=True,
    ).returncode == 0:
        subprocess.run(["ssh-add", str(key_path)], capture_output=True)
        return

    # Check if the key is already loaded in a running agent
    agent_keys = subprocess.run(["ssh-add", "-l"], capture_output=True, text=True)
    if agent_keys.returncode == 0:
        fp_out = subprocess.run(
            ["ssh-keygen", "-l", "-f", str(key_path)], capture_output=True, text=True
        ).stdout
        fp = fp_out.split()[1] if len(fp_out.split()) > 1 else ""
        if fp and fp in agent_keys.stdout:
            return  # Already loaded — nothing to do

    # Ask once with proper hidden input
    passphrase = getpass.getpass(f"  {C}SSH passphrase for {key_path.name}:{N} ")

    # Write a tiny askpass helper (lives only for the duration of ssh-add)
    fd, askpass = tempfile.mkstemp(prefix="dfai_", suffix=".sh")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(f'#!/bin/sh\nprintf "%s" {shlex.quote(passphrase)}\n')
        os.chmod(askpass, stat.S_IRWXU)

        # Start a new agent if none is running
        if not os.environ.get("SSH_AUTH_SOCK"):
            try:
                out = subprocess.check_output(["ssh-agent", "-s"], text=True)
                for line in out.splitlines():
                    m = re.match(r"(\w+)=([^;]+);", line)
                    if m:
                        os.environ[m.group(1)] = m.group(2)
            except Exception:
                pass

        env = {
            **os.environ,
            "SSH_ASKPASS": askpass,
            "SSH_ASKPASS_REQUIRE": "force",
            "DISPLAY": os.environ.get("DISPLAY") or "x",
        }
        result = subprocess.run(["ssh-add", str(key_path)], env=env, capture_output=True)
    finally:
        Path(askpass).unlink(missing_ok=True)

    passphrase = ""  # clear from memory (best effort)

    if result.returncode == 0:
        ok("SSH key loaded — no more passphrase prompts this session.")
    else:
        warn("Could not load key into agent — SSH will prompt as needed.")
    print()


def _run_ssh(cfg: dict, remote_cmd: str, check: bool = True) -> subprocess.CompletedProcess:
    cmd = ["ssh"] + _ssh_opts(cfg) + [cfg["vps_host"], remote_cmd]
    return subprocess.run(cmd, capture_output=True, text=True, check=check)


def _run_ssh_live(cfg: dict, remote_cmd: str) -> int:
    cmd = ["ssh"] + _ssh_opts(cfg) + [cfg["vps_host"], remote_cmd]
    return subprocess.run(cmd).returncode


def _rsync_to_vps(cfg: dict) -> None:
    ssh_cmd = "ssh " + " ".join(_ssh_opts(cfg))
    cmd = (
        ["rsync", "-az", "--delete"]
        + _RSYNC_EXCLUDE
        + ["-e", ssh_cmd, str(ROOT) + "/", f"{cfg['vps_host']}:{REMOTE_DIR}/"]
    )
    subprocess.run(cmd, check=True)


def _scp_env(cfg: dict) -> None:
    cmd = ["scp"] + _ssh_opts(cfg) + [str(ENV_FILE), f"{cfg['vps_host']}:{REMOTE_DIR}/.env"]
    subprocess.run(cmd, check=True)


# ── SSH helpers (Windows / paramiko) ─────────────────────────────────────────

def _paramiko_connect(cfg: dict):
    try:
        import paramiko
    except ImportError:
        err("paramiko is required on Windows.  Run:  pip install paramiko")
        sys.exit(1)
    host = cfg["vps_host"].split("@")[-1]
    user = cfg["vps_host"].split("@")[0] if "@" in cfg["vps_host"] else "root"
    key  = cfg.get("ssh_key", "")
    pwd  = cfg.get("ssh_pass", "")
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    if key and Path(key).exists():
        client.connect(host, username=user, key_filename=key)
    elif pwd:
        client.connect(host, username=user, password=pwd)
    else:
        err("No SSH key or password provided.")
        sys.exit(1)
    return client


def _paramiko_run(client, cmd: str) -> str:
    _, stdout, stderr = client.exec_command(cmd)
    out = stdout.read().decode()
    rc  = stdout.channel.recv_exit_status()
    if rc != 0:
        raise RuntimeError(f"Remote command failed:\n{stderr.read().decode()}")
    return out


def _sftp_upload_dir(client, local_root: Path, remote_dir: str) -> None:
    sftp = client.open_sftp()

    def _upload(local: Path, remote: str) -> None:
        for item in local.iterdir():
            if item.name in _SFTP_EXCLUDE or item.suffix in (".pyc", ".db"):
                continue
            rem_path = f"{remote}/{item.name}"
            if item.is_dir():
                try:
                    sftp.mkdir(rem_path)
                except OSError:
                    pass
                _upload(item, rem_path)
            else:
                sftp.put(str(item), rem_path)

    _upload(local_root, remote_dir)
    sftp.close()


# ── Port management ───────────────────────────────────────────────────────────

def _kill_port(port: int) -> None:
    if IS_WIN:
        try:
            out = subprocess.check_output(
                f"netstat -ano | findstr :{port}", shell=True, text=True
            )
            for line in out.splitlines():
                parts = line.split()
                if parts and parts[-1].isdigit():
                    subprocess.run(["taskkill", "/F", "/PID", parts[-1]],
                                   capture_output=True, check=False)
        except Exception:
            pass
    else:
        try:
            result = subprocess.run(
                ["lsof", "-ti", f"tcp:{port}"], capture_output=True, text=True
            )
            for pid in result.stdout.strip().splitlines():
                subprocess.run(["kill", pid.strip()], check=False)
            if result.stdout.strip():
                time.sleep(0.5)
        except Exception:
            pass


# ── Health check ──────────────────────────────────────────────────────────────

def _wait_for_proxy(port: int, timeout: int = 30) -> bool:
    url = f"http://localhost:{port}/health"
    for _ in range(timeout):
        try:
            with urllib.request.urlopen(url, timeout=2) as r:
                if r.status == 200:
                    return True
        except Exception:
            pass
        time.sleep(1)
    return False


# ── Tunnel ────────────────────────────────────────────────────────────────────

def _open_tunnel_unix(cfg: dict) -> subprocess.Popen:
    proxy_port = cfg.get("proxy_port", "5555")
    cmd = ["ssh"] + _ssh_opts(cfg) + [
        "-N", "-o", "ExitOnForwardFailure=yes",
        "-L", f"{proxy_port}:localhost:{proxy_port}",
        "-L", f"{OLLAMA_PORT}:localhost:{OLLAMA_PORT}",
        cfg["vps_host"],
    ]
    return subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def _open_tunnel_win(cfg: dict):
    import threading, socket, select
    client = _paramiko_connect(cfg)
    proxy_port = int(cfg.get("proxy_port", "5555"))
    transport = client.get_transport()

    def _pipe(sock, chan):
        while True:
            r, _, _ = select.select([sock, chan], [], [])
            if sock in r:
                d = sock.recv(4096)
                if not d: break
                chan.send(d)
            if chan in r:
                d = chan.recv(4096)
                if not d: break
                sock.send(d)
        sock.close()
        chan.close()

    def _forward(local_port: int, remote_port: int) -> None:
        srv = socket.socket()
        srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        srv.bind(("localhost", local_port))
        srv.listen(5)
        while True:
            try:
                conn, addr = srv.accept()
                chan = transport.open_channel(
                    "direct-tcpip", ("localhost", remote_port), addr
                )
                threading.Thread(target=_pipe, args=(conn, chan), daemon=True).start()
            except Exception:
                break

    for lp, rp in [(proxy_port, proxy_port), (OLLAMA_PORT, OLLAMA_PORT)]:
        threading.Thread(target=_forward, args=(lp, rp), daemon=True).start()

    return client  # caller holds reference; close() to shut down


# ── Dev / maintenance commands ────────────────────────────────────────────────

def do_setup() -> None:
    header("Setup — create venv and install dependencies")
    venv = ROOT / ".venv"
    if not venv.exists():
        info("Creating virtualenv...")
        subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True)
        ok("Virtualenv created")
    else:
        ok("Virtualenv already exists")
    pip = venv / ("Scripts" if IS_WIN else "bin") / "pip"
    info("Installing dependencies...")
    subprocess.run([str(pip), "install", "--upgrade", "pip", "-q"], check=True)
    subprocess.run([str(pip), "install", "-r", str(ROOT / "requirements.txt"), "-q"], check=True)
    (ROOT / "data").mkdir(exist_ok=True)
    ok("Setup complete")
    print()
    info("Next: pull the Ollama model and run the proxy:")
    info("  python3 wizard.py")


def do_test(integration: bool = False) -> None:
    header("Test")

    # wordfreq silently disables the common-word FP filter when missing.
    # That makes the false-positive tests pass incorrectly — catch it before pytest runs.
    try:
        import importlib
        importlib.import_module("wordfreq")
    except ModuleNotFoundError:
        err("wordfreq is not installed — tests would produce WRONG results without it.")
        err("The false-positive filter is disabled silently, causing FP tests to pass incorrectly.")
        print()
        err("Run:  python3 wizard.py setup   (or: pip install -r requirements.txt)")
        sys.exit(1)

    venv_pytest = ROOT / ".venv" / ("Scripts" if IS_WIN else "bin") / "pytest"
    pytest_bin  = str(venv_pytest) if venv_pytest.exists() else "pytest"
    cmd = [pytest_bin, "tests/", "-v", "--tb=short"]
    if integration:
        cmd.append("--integration")
        info("Full pipeline test: LLM (Ollama) + regex — make sure Ollama is running")
    else:
        info("Regex layer only — LLM is mocked. Run with --integration for the full pipeline.")
    sys.stdout.flush()
    env = dict(os.environ)
    env["PYTHONPATH"] = str(ROOT)
    result = subprocess.run(cmd, env=env, cwd=str(ROOT))
    if not integration and result.returncode == 0:
        print()
        warn("Reminder: this run did NOT test the LLM layer.")
        warn("Run  python3 wizard.py test --integration  (with Ollama active) to validate the full pipeline.")


def do_improve(cycles: int = 3, verbose: bool = False) -> None:
    header(f"Improve — auto-improvement loop ({cycles} cycles)")
    cmd = [sys.executable, "-m", "scripts.dev.auto_improve", "--cycles", str(cycles)]
    if verbose:
        cmd.append("--verbose")
    env = dict(os.environ)
    env["PYTHONPATH"] = str(ROOT)
    subprocess.run(cmd, env=env, cwd=str(ROOT))


def do_benchmark() -> None:
    header("Benchmark — Ollama model speed")
    env = dict(os.environ)
    env["PYTHONPATH"] = str(ROOT)
    subprocess.run([sys.executable, "-m", "scripts.dev.benchmark_ollama"], env=env, cwd=str(ROOT))


def do_docker(action: str) -> None:
    compose_file = ROOT / "docker-compose.yml"
    vps_file     = ROOT / "docker-compose.vps.yml"
    f = str(vps_file) if vps_file.exists() and not compose_file.exists() else str(compose_file)

    if action == "up":
        header("Docker — start containers")
        subprocess.run(["docker", "compose", "-f", f, "up", "-d"], cwd=str(ROOT), check=True)
        model = os.environ.get("OLLAMA_MODEL", "qwen3:1.7b")
        info(f"Pulling Ollama model {model} (first run may take a minute)...")
        subprocess.run(
            ["docker", "compose", "-f", f, "exec", "ollama", "ollama", "pull", model],
            cwd=str(ROOT), check=False,
        )
        ok("Stack running")
    elif action == "down":
        header("Docker — stop containers")
        subprocess.run(["docker", "compose", "-f", f, "down"], cwd=str(ROOT), check=True)
        ok("Stack stopped")
    else:
        err(f"Unknown docker action: {action}. Use: up | down")
        sys.exit(1)


def do_vault(action: str) -> None:
    if action == "stats":
        try:
            with urllib.request.urlopen("http://localhost:8080/health", timeout=3) as r:
                import json
                print(json.dumps(json.loads(r.read()), indent=2))
        except Exception:
            err("Proxy not reachable on localhost:8080. Is it running?")
    elif action == "clear":
        engagement = os.environ.get("ENGAGEMENT_ID", "")
        if not engagement:
            engagement = ask("Engagement ID to clear")
        if not ask_yn(f"Clear vault for '{engagement}'?", default=False):
            info("Cancelled.")
            return
        db = ROOT / "data" / "pii_vault.db"
        if not db.exists():
            err(f"Database not found: {db}")
            sys.exit(1)
        subprocess.run(
            ["sqlite3", str(db), f"DELETE FROM pii_vault WHERE engagement='{engagement}';"],
            check=True,
        )
        ok(f"Vault cleared for engagement '{engagement}'")
    else:
        err(f"Unknown vault action: {action}. Use: stats | clear")
        sys.exit(1)


def do_clean() -> None:
    header("Clean — remove build artifacts")
    patterns = [".venv", "__pycache__", "src/__pycache__", "tests/__pycache__", ".pytest_cache"]
    for p in patterns:
        target = ROOT / p
        if target.exists():
            import shutil as _shutil
            _shutil.rmtree(target)
            ok(f"Removed {p}")
    for pyc in ROOT.rglob("*.pyc"):
        pyc.unlink()
    ok("Clean complete")


# ── Local proxy ──────────────────────────────────────────────────────────────

def do_run_local(cfg: dict) -> None:
    port          = cfg.get("port", "8080")
    engagement_id = cfg.get("engagement_id", "default")

    venv_uvicorn = ROOT / ".venv" / "bin" / "uvicorn"
    uvicorn_bin  = str(venv_uvicorn) if venv_uvicorn.exists() else "uvicorn"

    env = dict(os.environ)
    env["ENGAGEMENT_ID"] = engagement_id
    env["PYTHONPATH"]    = str(ROOT)

    info(f"Starting proxy on localhost:{port}...")
    proc = subprocess.Popen(
        [uvicorn_bin, "src.main:app", "--host", "0.0.0.0", "--port", str(port)],
        env=env, cwd=str(ROOT),
        stdout=subprocess.DEVNULL, stderr=subprocess.PIPE,
    )

    def _stop():
        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                proc.kill()
        info("Proxy stopped.")

    atexit.register(_stop)

    if not _wait_for_proxy(int(port), timeout=15):
        out = proc.stderr.read().decode() if proc.stderr else ""
        err("Proxy failed to start.")
        if out:
            print(out[:500])
        sys.exit(1)

    ok(f"Proxy running on localhost:{port}")

    base_url  = f"http://localhost:{port}"
    claude_bin = shutil.which("claude")
    if not claude_bin:
        err("claude not found in PATH. Install Claude Code: https://claude.ai/code")
        info(f"Set ANTHROPIC_BASE_URL={base_url} and run claude manually.")
        sys.exit(1)

    claude_env = dict(os.environ)
    claude_env["ANTHROPIC_BASE_URL"] = base_url
    claude_env["ENGAGEMENT_ID"]      = engagement_id

    print()
    print(HR)
    print(f"{B}  Session active (local){N}")
    print(HR)
    print(f"  Engagement  : {engagement_id}")
    print(f"  Proxy       : {base_url}")
    print(HR)
    print()

    if not IS_WIN:
        old_sig = signal.signal(signal.SIGINT, signal.SIG_IGN)
    try:
        subprocess.run([claude_bin], env=claude_env, cwd=str(ROOT))
    finally:
        if not IS_WIN:
            signal.signal(signal.SIGINT, old_sig)


# ── Install global command ─────────────────────────────────────────────────────

def do_install() -> None:
    header(f"Install — global '{INSTALL_CMD}' command")
    wizard_path = ROOT.resolve() / "wizard.py"

    if IS_WIN:
        install_dir = Path(sys.executable).parent
        wrapper     = install_dir / f"{INSTALL_CMD}.bat"
        wrapper.write_text(f'@echo off\npython "{wizard_path}" %*\n')
        ok(f"Installed: {wrapper}")
    else:
        install_path = Path(f"/usr/local/bin/{INSTALL_CMD}")
        content      = f'#!/bin/sh\nexec python3 "{wizard_path}" "$@"\n'
        try:
            install_path.write_text(content)
            install_path.chmod(0o755)
        except PermissionError:
            import tempfile
            with tempfile.NamedTemporaryFile(mode="w", suffix=".sh", delete=False) as f:
                f.write(content)
                tmp = f.name
            subprocess.run(["sudo", "install", "-m", "755", tmp, str(install_path)], check=True)
            Path(tmp).unlink(missing_ok=True)
        ok(f"Installed: {install_path}")

    print()
    info("You can now run from any directory:")
    print(f"\n     {INSTALL_CMD}                 # full setup")
    print(f"     {INSTALL_CMD} connect          # open tunnel + launch Claude")
    print(f"     {INSTALL_CMD} deploy           # deploy to VPS")
    print(f"     {INSTALL_CMD} sync             # sync code updates")
    print()


# ── Deploy ────────────────────────────────────────────────────────────────────

def do_deploy(cfg: dict) -> None:
    header("Deploy — VPS")
    _prime_ssh_agent(cfg)
    vps        = cfg["vps_host"]
    proxy_port = cfg.get("proxy_port", "5555")
    info(f"Target     : {vps}")
    info(f"Remote dir : {REMOTE_DIR}")
    print()

    if IS_WIN:
        client = _paramiko_connect(cfg)
        info("Syncing project files...")
        _paramiko_run(client, f"mkdir -p {REMOTE_DIR}")
        _sftp_upload_dir(client, ROOT, REMOTE_DIR)
        ok("Sync done")
        info("Uploading .env...")
        sftp = client.open_sftp()
        sftp.put(str(ENV_FILE), f"{REMOTE_DIR}/.env")
        sftp.close()
        ok(".env uploaded")
        info("Checking Docker...")
        try:
            _paramiko_run(client, "docker --version && docker compose version")
        except RuntimeError:
            info("Installing Docker...")
            _paramiko_run(client, _DOCKER_INSTALL)
        ok("Docker ready")
        info("Starting containers...")
        try:
            _paramiko_run(client, f"cd {REMOTE_DIR} && docker compose -f docker-compose.vps.yml down --remove-orphans")
        except Exception:
            pass
        _paramiko_run(client, f"cd {REMOTE_DIR} && docker compose -f docker-compose.vps.yml up --build -d")
        ok("Containers started")
        client.close()
    else:
        info("Syncing project files...")
        _run_ssh(cfg, f"mkdir -p {REMOTE_DIR}")
        _rsync_to_vps(cfg)
        ok("Sync done")
        info("Uploading .env...")
        # Ensure PROXY_SECRET is stripped before upload — it breaks the Anthropic SDK
        # (TypeScript URL resolution discards any base URL path prefix).
        if ENV_FILE.exists():
            cleaned = "\n".join(
                l for l in ENV_FILE.read_text().splitlines()
                if not l.startswith("PROXY_SECRET=")
            ) + "\n"
            ENV_FILE.write_text(cleaned)
        _scp_env(cfg)
        ok(".env uploaded")
        info("Checking Docker...")
        if _run_ssh(cfg, "docker --version 2>/dev/null && docker compose version 2>/dev/null", check=False).returncode != 0:
            info("Installing Docker...")
            _run_ssh_live(cfg, _DOCKER_INSTALL)
        ok("Docker ready")
        info(f"Blocking port {proxy_port} from external access (SSH tunnel only)...")
        _run_ssh(cfg, (
            f"which ufw >/dev/null 2>&1 || apt-get install -y -q ufw; "
            f"ufw allow 22/tcp >/dev/null 2>&1; "
            f"ufw deny {proxy_port}/tcp >/dev/null 2>&1; "
            f"ufw --force enable >/dev/null 2>&1"
        ), check=False)
        ok("Firewall configured")
        info("Starting containers...")
        # Bring down first to release port bindings cleanly, then rebuild.
        # Sleep gives the kernel time to release TCP ports before docker re-binds them.
        _run_ssh(cfg, f"cd {REMOTE_DIR} && docker compose -f docker-compose.vps.yml down --remove-orphans --timeout 15 2>&1; sleep 3", check=False)
        _run_ssh_live(cfg, f"cd {REMOTE_DIR} && docker compose -f docker-compose.vps.yml up --build -d")
        ok("Containers started")

    # Wait for proxy via a temporary tunnel
    info("Waiting for proxy to come up (first run pulls the Ollama model — may take a minute)...")
    if not IS_WIN:
        tunnel = _open_tunnel_unix(cfg)
        try:
            if _wait_for_proxy(int(proxy_port), timeout=90):
                ok("Proxy healthy")
            else:
                warn("Proxy didn't respond in 90s — it may still be pulling the model.")
                info(f"Check: ssh {vps} 'cd {REMOTE_DIR} && docker compose -f docker-compose.vps.yml logs -f proxy'")
        finally:
            tunnel.terminate()
            tunnel.wait()


# ── Sync ─────────────────────────────────────────────────────────────────────

def do_sync(cfg: dict) -> None:
    header("Sync — push code to VPS and rebuild proxy")
    _prime_ssh_agent(cfg)
    info("Syncing files...")
    if IS_WIN:
        client = _paramiko_connect(cfg)
        _sftp_upload_dir(client, ROOT, REMOTE_DIR)
        ok("Sync done")
        info("Rebuilding proxy container...")
        _paramiko_run(client, (
            f"cd {REMOTE_DIR} && "
            "docker compose -f docker-compose.vps.yml build proxy --quiet && "
            "docker compose -f docker-compose.vps.yml up -d --no-deps proxy"
        ))
        client.close()
    else:
        _rsync_to_vps(cfg)
        ok("Sync done")
        info("Rebuilding proxy container...")
        _run_ssh_live(cfg, (
            f"cd {REMOTE_DIR} && "
            "docker compose -f docker-compose.vps.yml build proxy --quiet 2>&1 | tail -3 && "
            "docker compose -f docker-compose.vps.yml up -d --no-deps proxy"
        ))
    ok("Proxy rebuilt and restarted")


# ── Connect ───────────────────────────────────────────────────────────────────

def do_connect(cfg: dict) -> None:
    proxy_port    = int(cfg.get("proxy_port", "5555"))
    engagement_id = cfg.get("engagement_id", "default")

    header("Connect — opening tunnel and launching Claude")
    _prime_ssh_agent(cfg)

    # Security: SSH tunnel + UFW port blocking protect the proxy.
    # Path-based secrets don't work because the Anthropic SDK constructs
    # URLs with absolute paths that replace any base URL path component.
    base_url  = f"http://localhost:{proxy_port}"

    # Free stale port bindings
    for port in [proxy_port, OLLAMA_PORT]:
        _kill_port(port)

    # Open tunnel
    info(f"Opening SSH tunnel to {cfg['vps_host']}...")
    info(f"  localhost:{proxy_port}  → VPS:{proxy_port}  (proxy)")
    info(f"  localhost:{OLLAMA_PORT} → VPS:{OLLAMA_PORT} (Ollama)")

    tunnel_proc   = None
    tunnel_client = None

    if IS_WIN:
        tunnel_client = _open_tunnel_win(cfg)
    else:
        tunnel_proc = _open_tunnel_unix(cfg)

    def _cleanup() -> None:
        if tunnel_proc and tunnel_proc.poll() is None:
            tunnel_proc.terminate()
            try:
                tunnel_proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                tunnel_proc.kill()
        if tunnel_client:
            try:
                tunnel_client.close()
            except Exception:
                pass
        print(f"\n  {Y}▸{N}  Tunnel closed.")

    atexit.register(_cleanup)

    # Wait for proxy
    info("Waiting for proxy...")
    if not _wait_for_proxy(proxy_port, timeout=30):
        err("Proxy didn't respond in 30s. Is the VPS stack running?")
        info("Run:  python3 wizard.py deploy")
        sys.exit(1)
    ok(f"Proxy ready")

    # Resolve working directory
    pentest_dir = cfg.get("pentest_dir", "")
    launch_dir  = pentest_dir or str(Path.home() / "pentests" / engagement_id)
    Path(launch_dir).mkdir(parents=True, exist_ok=True)

    # Session summary
    print()
    print(HR)
    print(f"{B}  Session active{N}")
    print(HR)
    print(f"  Engagement  : {engagement_id}")
    print(f"  Proxy       : {base_url}")
    print(f"  Working dir : {C}{launch_dir}{N}")
    print(HR)
    print()

    # Launch Claude
    claude_bin = shutil.which("claude")
    if not claude_bin:
        err("claude not found in PATH. Install Claude Code first: https://claude.ai/code")
        sys.exit(1)

    env = dict(os.environ)
    env["ANTHROPIC_BASE_URL"] = base_url
    env["ENGAGEMENT_ID"]      = engagement_id
    env["OLLAMA_HOST"]        = f"http://localhost:{OLLAMA_PORT}"

    # Smoke test: verify Claude can reach the proxy before opening the full session
    info("Testing proxy → Claude connection...")
    try:
        test = subprocess.run(
            [claude_bin, "-p", "reply with exactly: proxy ok"],
            env=env, cwd=launch_dir,
            capture_output=True, text=True, timeout=30,
        )
        output = (test.stdout + test.stderr).strip()
        if test.returncode == 0 and "403" not in output and "Forbidden" not in output:
            ok("Proxy connection verified.")
        else:
            err("Proxy test failed. Claude returned:")
            print(f"\n    {output[:300]}\n")
            if "403" in output or "missing proxy token" in output:
                warn("The proxy is rejecting requests (403).")
                warn("The running container may still have PROXY_SECRET set from a previous deploy.")
                warn("Fix: python3 wizard.py → Deploy (will restart containers cleanly).")
            sys.exit(1)
    except subprocess.TimeoutExpired:
        warn("Smoke test timed out — launching Claude anyway.")
    except Exception as e:
        warn(f"Smoke test skipped: {e}")

    # Let Claude handle Ctrl+C itself; restore after it exits
    if not IS_WIN:
        old_sigint = signal.signal(signal.SIGINT, signal.SIG_IGN)
    try:
        subprocess.run([claude_bin], env=env, cwd=launch_dir)
    finally:
        if not IS_WIN:
            signal.signal(signal.SIGINT, old_sigint)


# ── Tunnel only ───────────────────────────────────────────────────────────────

def do_tunnel(cfg: dict) -> None:
    proxy_port = int(cfg.get("proxy_port", "5555"))

    header("Tunnel — SSH only")
    _prime_ssh_agent(cfg)

    for port in [proxy_port, OLLAMA_PORT]:
        _kill_port(port)

    info(f"Opening SSH tunnel to {cfg['vps_host']}...")
    tunnel_proc = _open_tunnel_unix(cfg)

    def _cleanup() -> None:
        if tunnel_proc.poll() is None:
            tunnel_proc.terminate()
            try:
                tunnel_proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                tunnel_proc.kill()
        info("Tunnel closed.")

    atexit.register(_cleanup)

    if not _wait_for_proxy(proxy_port, timeout=30):
        err("Proxy didn't respond. Is the VPS stack running?")
        sys.exit(1)

    ok(f"Tunnel ready — localhost:{proxy_port}")
    info("Press Ctrl+C to close tunnel.")

    try:
        tunnel_proc.wait()
    except KeyboardInterrupt:
        pass


# ── Main wizard ───────────────────────────────────────────────────────────────

def _wizard_existing(cfg: dict) -> None:
    """Action menu for a previously configured engagement."""
    engagement_id = cfg.get("engagement_id", "?")

    ok(f"Loaded saved configuration for '{engagement_id}'")
    print()
    print(f"  VPS Host   : {cfg.get('vps_host', 'N/A')}")
    print(f"  Proxy Port : {cfg.get('proxy_port', '5555')}")
    print(f"  SSH Key    : {cfg.get('ssh_key', 'default')}")
    print(f"  Model      : {cfg.get('ollama_model', 'N/A')}")
    print()
    print(f"  {B}What would you like to do?{N}\n")
    print(f"  {B}[1]{N} Connect   — open SSH tunnel and launch Claude")
    print(f"  {B}[2]{N} Deploy    — re-deploy to VPS (rebuilds containers)")
    print(f"  {B}[3]{N} Sync      — push code updates + rebuild proxy container")
    print()
    action = ask("Choice", default="1")
    print()

    if action == "1":
        do_connect(cfg)
    elif action == "2":
        do_deploy(cfg)
        print()
        if ask_yn("Open tunnel and launch Claude now?", default=True):
            print()
            do_connect(cfg)
        else:
            info("When ready:  python3 wizard.py connect")
    elif action == "3":
        do_sync(cfg)
    else:
        err("Unknown choice — exiting.")


def wizard(initial_engagement: str = "") -> None:
    header(f"DontFeedTheAI — Setup Wizard  ({SYSTEM} {platform.machine()})")

    # ── 0. New or existing engagement ─────────────────────────────────────────
    if not initial_engagement:
        saved = _load_env()
        saved_id  = saved.get("engagement_id", "")
        saved_vps = saved.get("vps_host", "")
        has_saved = bool(saved_id and saved_vps)

        print(f"  {B}Select an engagement:{N}\n")
        print(f"  {B}[1]{N} New engagement  — configure everything from scratch.")
        if has_saved:
            print(f"  {B}[2]{N} {saved_id}  ({saved_vps})")
        print()

        default_choice = "2" if has_saved else "1"
        flow = ask("Choice", default=default_choice)
        print()

        if flow == "2" and has_saved:
            _wizard_existing(saved)
            return
        else:
            default_name = f"pentest-{datetime.now().strftime('%Y%m%d')}"
            initial_engagement = ask("Engagement / client name", default=default_name)

    # ── 1. Deployment mode ────────────────────────────────────────────────────
    print(f"\n  {B}Deployment mode:{N}\n")
    print(f"  {B}[1]{N} VPS         — recommended. Proxy + Ollama run remotely, SSH tunnel to localhost.")
    print(f"  {B}[2]{N} Local       — everything on this machine (Apple Silicon / Linux).")
    print(f"  {B}[3]{N} Docker      — fully containerized, local.\n")
    mode = ask("Choice", default="1")

    mode_name = {"1": "vps", "2": "local", "3": "docker"}.get(mode, "local")
    cfg: dict = {"engagement_id": initial_engagement, "deploy_mode": mode_name}

    # ── 2. VPS config ─────────────────────────────────────────────────────────
    if mode == "1":
        print()
        cfg["vps_host"]   = ask("VPS address (e.g. root@1.2.3.4)")
        cfg["proxy_port"] = ask("Proxy port", default="5555")

        print()
        if not IS_WIN:
            # Suggest the first standard SSH key that exists on this machine.
            ssh_dir = Path.home() / ".ssh"
            default_key = next(
                (str(ssh_dir / name) for name in ("id_ed25519", "id_rsa", "id_ecdsa")
                 if (ssh_dir / name).exists()),
                str(ssh_dir / "id_ed25519"),
            )
            if not ssh_available():
                warn("ssh not found in PATH — install OpenSSH or use WSL.")
            cfg["ssh_key"] = ask("SSH private key path", default=default_key)
        else:
            if ssh_available():
                ok("OpenSSH detected — using system ssh")
                cfg["ssh_key"] = ask("SSH private key path (leave blank to use password)", default="")
            if not cfg.get("ssh_key"):
                warn("No SSH key — will use password authentication (requires paramiko).")
                cfg["ssh_pass"] = ask("VPS root password", secret=True)

    # ── 3. Pentest working directory ──────────────────────────────────────────
    if mode == "1":
        default_dir = str(Path.home() / "pentests" / cfg["engagement_id"])
        print()
        info("Claude will launch from this directory (keeps your pentest files isolated).")
        cfg["pentest_dir"] = ask("Working directory", default=default_dir)

    # ── 4. Ollama model ───────────────────────────────────────────────────────
    print()
    ram_gb = detect_ram_gb()
    model  = suggest_model(ram_gb)
    if ram_gb:
        info(f"Detected RAM: {ram_gb:.1f} GB → suggested model: {model}")
    else:
        info(f"Could not detect RAM — defaulting to {model}")
    cfg["ollama_model"] = ask("Ollama model", default=model)

    # ── 5. Write .env.vps ─────────────────────────────────────────────────────
    print()
    write_env(cfg)

    # ── 6. Next steps ─────────────────────────────────────────────────────────
    if mode == "1":
        print()
        if ask_yn("Deploy to VPS now?", default=True):
            print()
            do_deploy(cfg)
            print()
            if ask_yn("Open tunnel and launch Claude now?", default=True):
                print()
                do_connect(cfg)
            else:
                info("When ready:  python3 wizard.py connect")
        else:
            print()
            info("When ready:")
            info("  python3 wizard.py deploy   # deploy to VPS")
            info("  python3 wizard.py connect  # open tunnel + launch Claude")

    elif mode == "2":
        print()
        if ask_yn("Start proxy and launch Claude now?", default=True):
            print()
            do_run_local(cfg)
        else:
            info("To start manually:\n")
            if IS_WIN:
                print(f"     set ENGAGEMENT_ID={cfg['engagement_id']}")
                print(f"     python -m uvicorn src.main:app --host 0.0.0.0 --port 8080")
                print(f"     set ANTHROPIC_BASE_URL=http://localhost:8080")
                print(f"     claude")
            else:
                print(f"     ENGAGEMENT_ID={cfg['engagement_id']} uvicorn src.main:app --host 0.0.0.0 --port 8080")
                print(f"     # in another terminal:")
                print(f"     ANTHROPIC_BASE_URL=http://localhost:8080 claude")

    elif mode == "3":
        print()
        info("To start with Docker:\n")
        if IS_WIN:
            print(f"     set ENGAGEMENT_ID={cfg['engagement_id']}")
            print(f"     docker compose up -d")
            print(f"     set ANTHROPIC_BASE_URL=http://localhost:8080")
            print(f"     claude")
        else:
            print(f"     ENGAGEMENT_ID={cfg['engagement_id']} docker compose up -d")
            print(f"     ANTHROPIC_BASE_URL=http://localhost:8080 claude")

    print()


# ── Entry point ───────────────────────────────────────────────────────────────

def _print_help() -> None:
    print(f"\n{B}DontFeedTheAI — wizard.py{N}\n")
    print(f"  {B}python3 wizard.py{N}                     interactive setup (start here)")
    print(f"  {B}python3 wizard.py connect{N}             open tunnel + launch Claude")
    print(f"  {B}python3 wizard.py deploy{N}              full deploy to VPS")
    print(f"  {B}python3 wizard.py sync{N}                push code updates to VPS")
    print(f"  {B}python3 wizard.py tunnel{N}              SSH tunnel only")
    print(f"  {B}python3 wizard.py install{N}             install 'dfai' global command")
    print(f"  {B}python3 wizard.py setup{N}               create venv + install dependencies")
    print(f"  {B}python3 wizard.py test{N}                run tests")
    print(f"  {B}python3 wizard.py improve{N}             run anonymization improvement loop")
    print(f"  {B}python3 wizard.py docker up|down{N}      manage Docker stack")
    print(f"  {B}python3 wizard.py vault stats|clear{N}   inspect or reset surrogate DB")
    print(f"  {B}python3 wizard.py clean{N}               remove build artifacts")
    print()


def _require_env(cmd: str) -> dict:
    cfg = _load_env()
    if not cfg.get("vps_host"):
        err(f"{ENV_FILE.name} not found or VPS_HOST not set. Run: python3 wizard.py")
        sys.exit(1)
    return cfg


def main() -> None:
    args = sys.argv[1:]

    if not args:
        wizard()
        return

    if args[0] in ("--help", "-h", "help"):
        _print_help()
        return

    cmd = args[0].lower()

    if cmd == "new":
        name = args[1] if len(args) > 1 else ""
        wizard(initial_engagement=name)

    elif cmd == "deploy":
        do_deploy(_require_env("deploy"))

    elif cmd == "sync":
        do_sync(_require_env("sync"))

    elif cmd == "connect":
        do_connect(_require_env("connect"))

    elif cmd == "tunnel":
        do_tunnel(_require_env("tunnel"))

    elif cmd == "install":
        do_install()

    elif cmd == "setup":
        do_setup()

    elif cmd == "test":
        do_test(integration="--integration" in args)

    elif cmd == "improve":
        cycles  = int(next((args[i+1] for i, a in enumerate(args) if a == "--cycles"), 3))
        verbose = "--verbose" in args
        do_improve(cycles=cycles, verbose=verbose)

    elif cmd == "benchmark":
        do_benchmark()

    elif cmd == "docker":
        action = args[1] if len(args) > 1 else ""
        do_docker(action)

    elif cmd == "vault":
        action = args[1] if len(args) > 1 else "stats"
        do_vault(action)

    elif cmd == "clean":
        do_clean()

    else:
        print(f"Unknown command: {cmd}")
        print("Usage: python3 wizard.py [setup | deploy | sync | connect | tunnel")
        print("                          install | test [--integration] | improve [--cycles N]")
        print("                          benchmark | docker <up|down> | vault <stats|clear> | clean]")
        sys.exit(1)


if __name__ == "__main__":
    main()
